version: "3"
networks:
  etcdcluster:
    driver: bridge
services:
  etcd1:
    image: bitnami/etcd:3.4.13
    container_name: etcd1
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://0.0.0.0:2379
    command: etcd
      --name etcd1
      --listen-peer-urls http://localhost:2380
      --initial-advertise-peer-urls http://etcd1:2380
      --initial-cluster-state new
      --initial-cluster-token etcd-2pc
    ports:
      - "12379:2379"
      - "12380:2380"
    expose:
      - "2379"
      - "2380"
    networks:
      - etcdcluster
    volumes:
      - etcd1

volumes:
  etcd1:
